databases:
  - name: exam_system_db
    databaseName: exam_system_db
    user: exam_system_user
    plan: free

services:
  - type: web
    name: exam-system-uss
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn exam_system.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: exam_system_db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
